c_compiler:
  - gcc                        # [linux]
  - clang                      # [osx]
  - vs2008                     # [win]
  - vs2015                     # [win]
  - vs2015                     # [win]
  - vs2015                     # [win]
c_compiler_version:            # [unix]
  - 9                          # [osx]
  - 7                          # [linux64 or aarch64]
  - 8                          # [ppc64le or armv7l]
cxx_compiler:
  - gxx                        # [linux]
  - clangxx                    # [osx]
  - vs2008                     # [win]
  - vs2015                     # [win]
  - vs2015                     # [win]
  - vs2015                     # [win]
cxx_compiler_version:          # [unix]
  - 9                          # [osx]
  - 7                          # [linux64 or aarch64]
  - 8                          # [ppc64le or armv7l]

python:
  - 2.7.* *_cpython  # [not (aarch64 or ppc64le)]
  - 3.6.* *_cpython
  - 3.7.* *_cpython
  - 3.8.* *_cpython
python_impl:
  - cpython
vc:                    # [win]
  - 9                  # [win]
  - 14                 # [win]
  - 14                 # [win]
  - 14                 # [win]

zip_keys:
  -
    - python
    - vc                        # [win]
    - c_compiler                # [win]
    - cxx_compiler              # [win]
